### ISSUE TITLE
“module ”has no attribute of PSROIpooling

### ISSUE THREAD

**Issue by Suodislie** [terrychenism/mx-rfcn#2]
When i run the project MX-rfcn(python train_end2end_resnext.py)，i got a problem  ,It  said “ 'module'has no attribute of PSROIpooling",everything that i should prepare is ready,what should i do,thanks for your help.

**Comment by Suodislie** [comment]
Yes,i use this mxnet,and all steps i did is according to 'Training and Testing R-FCN' in the file  'readme.md', and there was no issue when i compiled mxnet, what else i should try. thanks for your reply!

**Comment by terrychenism** [comment]
Did you use GPU mode? I haven't implemented PSROI cpu code.

**Comment by Suodislie** [comment]
I see ! you touch the spot !  I use cpu mode, because something going wrong when i compiled mxnet with GPU. I will try again ,thanks for your reply agian!

**Comment by Suodislie** [comment]
there are smething wrong when i compiled mxnet with gpu, one of errors is as follows:
**/usr/include/c++/4.9/bits/hashtable_policy.h:1976:1: error: object type ‘std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const std::basic_string<char>, dmlc::json::AnyJSONManager::Entry>, true> > >::__node_type {aka std::__detail::_Hash_node<std::pair<const std::basic_string<char>, dmlc::json::AnyJSONManager::Entry>, true>}’ does not match destructor name ~‘value_type’
Makefile:185: recipe for target 'build/src/operator/elementwise_binary_scalar_op_gpu.o' failed
make: *** [build/src/operator/elementwise_binary_scalar_op_gpu.o] Error 1**
i have done 'git checkout rfcnrebase' and the version of compiler is 4.9 ,I also have tried the version 4.7 and 5.3 , but it  still not work . Looking forward to your reply.

**Comment by Suodislie** [comment]
what is the cuda version you used？ I double that whether the cuda version is  suitable，I
 use the 7.0 version cuda.

**Comment by terrychenism** [comment]
cuda7.5

**Comment by Franciszzj** [comment]
I got this problem too. And I use gpu model, it's there something wrong? I followed the README to setup this project.

Traceback (most recent call last):
  File "train_end2end_resnext.py", line 239, in <module>
    main()
  File "train_end2end_resnext.py", line 126, in main
    sym = resnext_101(num_class=args.num_classes, bn_mom=args.bn_mom, bn_global=True, is_train=True) 
  File "/media/dl/dl/workspace/mx-rfcn-master/rcnn/resnext.py", line 332, in resnext_101
    num_anchor=12, bottle_neck=True, bn_mom=bn_mom, bn_global=bn_global, workspace=512, is_train=is_train)
  File "/media/dl/dl/workspace/mx-rfcn-master/rcnn/resnext.py", line 277, in resnext_rfcn
    psroipooled_loc_rois = mx.symbol.PSROIPooling(name='psroipooled_loc_rois', data=rfcn_bbox, rois=rois[0], group_size=7, output_dim=8, spatial_scale=0.0625)
AttributeError: 'module' object has no attribute 'PSROIPooling'

**Comment by terrychenism** [comment]
did you use rfcn-rebase branch?

**Comment by Franciszzj** [comment]
Yes， I followed the README to setup this project.

**Comment by Franciszzj** [comment]
But when I visualize the feature map at different layer，it‘s all dark! There is only little feature that have learned.

**Comment by terrychenism** [comment]
git checkout rfcn-rebase?

**Comment by Franciszzj** [comment]
I just run a command like this：
git clone --recursive https://github.com/terrychenism/mxnet.git && cd mxnet && git checkout rfcn-rebase && make -j8

**Comment by terrychenism** [comment]
Could you check the psroipooling.cu/ cc/ .h in src/operator folder?

**Comment by Franciszzj** [comment]
Yes，there are three files：psroi_pooling.cc/cu, psroi_pooling-inl.h
