### ISSUE TITLE
infer_shape error

### ISSUE THREAD

**Issue by arlose** [terrychenism/mx-rfcn#3]
terry:
python train_end2end_resnext.py --gpus 0 --num-classes 5
INFO:root:############### TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END ##################
          -----------------------------------------------------------------------------------
INFO:root:Namespace(bn_mom=0.99, dataset_root='/home/xxx/Work/mx-rfcn/data', devkit_path='/home/xxx/Work/mx-rfcn/data/VOCdevkit', factor_step=50000, frequent=20, gpu_ids='0', image_set='trainval', kv_store='device', load_epoch=0, lr=0.001, mom=0.9, monitor=False, need_mean=False, no_flip=False, no_shuffle=False, num_classes=5, num_epoch=10, outdata_path='/home/xxx/Work/mx-rfcn/data', prefix='/home/xxx/Work/mx-rfcn/model/faster-resnext-101', pretrained='/home/xxx/Work/mx-rfcn/model/resnext-101', resume=False, root_path='/home/xxx/Work/mx-rfcn/data', test_image_set='test', train_rfcn=True, wd=0.0005, year='2007')

          -----------------------------------------------------------------------------------
INFO:root:########## TRAIN R-FCN WITH APPROXIMATE JOINT END2END #############
wrote gt roidb to /home/xxx/Work/mx-rfcn/data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
{'bbox_target': (1, 48L, 36L, 64L), 'im_info': (1, 3L), 'bbox_inside_weight': (1, 48L, 36L, 64L), 'bbox_outside_weight': (1, 48L, 36L, 64L), 'gt_boxes': (1, 5L), 'label': (1, 27648L), 'data': (1, 3L, 576L, 1024L)}
[10:49:00] /home/xxx/Work/mxnet_rfcn/dmlc-core/include/dmlc/logging.h:235: [10:49:00] src/operator/./reshape-inl.h:288: Check failed: (new_size % proposed_dim) == (0) Illegal dim setting, can't be divided.
infer_shape error. Arguments:
  bbox_target: (1, 48L, 36L, 64L)
  im_info: (1, 3L)
  bbox_inside_weight: (1, 48L, 36L, 64L)
  label: (1, 27648L)
  gt_boxes: (1, 5L)
  bbox_outside_weight: (1, 48L, 36L, 64L)
  data: (1, 3L, 576L, 1024L)
Traceback (most recent call last):
  File "train_end2end_resnext.py", line 239, in <module>
    main()
  File "train_end2end_resnext.py", line 147, in main
    args_params, auxs_params= init_model(args_params, auxs_params, train_data, sym, args.pretrained)
  File "train_end2end_resnext.py", line 59, in init_model
    arg_shape, _, _ = sym.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 459, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 526, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in cls_score_reshape: [10:49:00] src/operator/./reshape-inl.h:288: Check failed: (new_size % proposed_dim) == (0) Illegal dim setting, can't be divided.

**Comment by arlose** [comment]
when i use python train_end2end_resnext.py --gpus 0 --num-classes 21 or no --num-classes is OK.
but the data is only 5 classes

**Comment by terrychenism** [comment]
Please follow the instruction, make sure VOC07 experiment is okay

**Comment by arlose** [comment]
VOC07 experiment is okay
when i use my own data, I have the error like above

**Comment by arlose** [comment]
my own data have only 5 classes

**Comment by terrychenism** [comment]
You need to change some parameters in conv layers follow by rpn.

**Comment by arlose** [comment]
these?：
if is_train:
        psroipooled_cls_rois = mx.symbol.PSROIPooling(name='psroipooled_cls_rois', data=rfcn_cls, rois=rois[0], group_size=7, output_dim=5, spatial_scale=0.0625) # output_dim=21
    else:
        psroipooled_cls_rois = mx.symbol.PSROIPooling(name='psroipooled_cls_rois', data=rfcn_cls, rois=rpn_roi, group_size=7, output_dim=5, spatial_scale=0.0625) # output_dim=21

**Comment by arlose** [comment]
in resnext.py
line 283 and 285
output_dim=num_class

**Comment by terrychenism** [comment]
try this quick fix: https://github.com/terrychenism/mx-rfcn/commit/8ed907e7f8d5ea2d100cb041d09a74d9388d654c

**Comment by arlose** [comment]
thanks！
