### ISSUE TITLE
If there a pretrained rfcn model use renext-101?

### ISSUE THREAD

**Issue by Trangle** [terrychenism/mx-rfcn#4]
I cannot recurrent the result using voc 2007 to reach the mAP 73.44.

**Comment by terrychenism** [comment]
I can upload the pretrained model tomorrow.   What's your result in mAP?

**Comment by Trangle** [comment]
@terrychenism about 43.4

**Comment by terrychenism** [comment]
I have uploaded the model, Download link to r-fcn-resnext101 model  Onedrive: https://1drv.ms/u/s!Aqd-q_R495LrljchqMVhnv5ubF2O symbol：https://1drv.ms/u/s!Aqd-q_R495LrljY3o_udXofNNmiw
mAP should be 74.19. Please check it

**Comment by Trangle** [comment]
@terrychenism thank you very much, I will check it now.

**Comment by xinghedyc** [comment]
@Trangle Have you achieved mAP 74.19 with training a model by yourself ?
I just got a mAP 43.7 by training for 11 epochs.

**Comment by terrychenism** [comment]
Yes, could you download the pretrain model to test?

**Comment by Trangle** [comment]
@xinghedyc Not yet, I got the same problem with you.

**Comment by xinghedyc** [comment]
@terrychenism I can get mAP 74.19 with given checkpoint above, but I'm concerned about how to achieve this, I mean the training process or some tricks? because the default setting for train_end2end-resnext.py seems can't easily get mAP 74.19

**Comment by terrychenism** [comment]
Yes,  the provided code should get ~74.  You can show your test result to check the code.
