### ISSUE TITLE
resnet18

### ISSUE THREAD

**Issue by kaishijeng** [terrychenism/mx-rfcn#5]
I want to use resnet18 as base model for RFCN.
What steps I should do in order to train resnet18-based RFCN?
From README.md, it seems that I need to download pretrained resnet18 imagenet model from the link below and run train_end2end_resnet.py --gpus 0.
http://data.mxnet.io/models/imagenet/resnet/18-layers/

Is this correct?

Thanks,

**Comment by terrychenism** [comment]
Yes

**Comment by kaishijeng** [comment]
Terry

Default resnet-50 is running OK with the following command:
python train_end2end_resnet.py --gpus 0
.
But if I change pretrained mode from resnet-50 to resnet-18 in
train_end2end_resnet.py and use the same command to run, I got the
following error. What else do I need to change to use resnet18 in
train_end2end_resnet.py?

INFO:root:############### TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END
##################

-----------------------------------------------------------------------------------
INFO:root:Namespace(bn_mom=0.99,
dataset_root='/home/fc/2TB/src/mx-rfcn/data',
devkit_path='/home/fc/2TB/src/mx-rfcn/data/VOCdevkit', factor_step=50000,
freque20, gpu_ids='0', image_set='trainval', kv_store='device',
load_epoch=0, lr=0.001, mom=0.9, need_mean=False, no_flip=False,
no_shuffle=False, num_classes=21, nupoch=10,
outdata_path='/home/fc/2TB/src/mx-rfcn/data',
prefix='/home/fc/2TB/src/mx-rfcn/model/faster-resnet-18',
pretrained='/home/fc/2TB/src/mx-rfcn/model/res-18', resume=False,
root_path='/home/fc/2TB/src/mx-rfcn/data', test_image_set='test',
wd=0.0005, year='2007')


-----------------------------------------------------------------------------------
INFO:root:########## TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END
#############
voc_2007_trainval gt roidb loaded from
/home/fc/2TB/src/mx-rfcn/data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
Traceback (most recent call last):
  File "train_end2end_resnet.py", line 186, in <module>
    main()
  File "train_end2end_resnet.py", line 133, in main
    begin_epoch=args.load_epoch, num_epoch=args.num_epoch)
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py",
line 360, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "/home/fc/2TB/src/mx-rfcn/rcnn/module.py", line 95, in init_params
    force_init=force_init)
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py",
line 198, in init_params
    _impl(name, arr, arg_params)
  File
"/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py",
line 191, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: stage3_unit2_bn3_beta is not presented

**Comment by terrychenism** [comment]
Is it something wrong for using bottleneck? I will check it soon.
