### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PSROIPooling'

### ISSUE THREAD

**Issue by breeze5428** [terrychenism/mx-rfcn#6]
Hi,
I train mx-rfcn by running `python train_end2end_resnext.py --gpus 0`.  Then, I encountered this error as follows:

> INFO:root:########## TRAIN R-FCN WITH APPROXIMATE JOINT END2END #############
> Traceback (most recent call last):
>   File "train_end2end_resnext.py", line 239, in <module>
>     main()
>   File "train_end2end_resnext.py", line 126, in main
>     sym = resnext_101(num_class=args.num_classes, bn_mom=args.bn_mom, bn_global=True, is_train=True) 
>   File "/home/weiliu/projects/traffSgn/mx-rfcn/rcnn/resnext.py", line 332, in resnext_101
>     num_anchor=12, bottle_neck=True, bn_mom=bn_mom, bn_global=bn_global, workspace=512, is_train=is_train)
>   File "/home/weiliu/projects/traffSgn/mx-rfcn/rcnn/resnext.py", line 277, in resnext_rfcn
>     psroipooled_loc_rois = mx.symbol.PSROIPooling(name='psroipooled_loc_rois', data=rfcn_bbox, rois=rois[0], group_size=7, output_dim=8, spatial_scale=0.0625)
> AttributeError: 'module' object has no attribute 'PSROIPooling'

Could you give any advices. Thank you in advance.

**Comment by terrychenism** [comment]
plz use https://github.com/terrychenism/mxnet/tree/rfcn-rebase

**Comment by breeze5428** [comment]
Thank you for reply.   I find that I installed the`  dmlc mxnet`,  which caused the error.Now, I able to  train.

To use dmlc mxnet,  maybe I should copy psroi_pooling.cc psroi_pooling.cu and psroi_pooling-inl.h in operator to mxnet/src/operator.

**Comment by terrychenism** [comment]
sure

**Comment by breeze5428** [comment]
When run command  `python test.py --has_rpn --prefix model/final --epoch 8`,  an error occurred  as follows:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    args.has_rpn)
  File "/home/mx-rfcn/tools/test_rcnn.py", line 23, in test_rcnn
    config.PIXEL_MEANS = np.array([[[0,0,0]]])
NameError: global name 'np' is not defined

I think it is better to add   `import numpy as np`  in the file test_rcnn.py    .
