### ISSUE TITLE
How to test resnet  trained by train_end2end_resnet.py

### ISSUE THREAD

**Issue by breeze5428** [terrychenism/mx-rfcn#8]
Hi, Terry!

Thank you for sharing your project selflessly.

I met some difficulties:
1. How to test resnet  trained by _train_end2end_resnet.py_?   Is  it need to modify many code?
2. How to begin  a  new training with a specific epoch for _train_end2end_resnext.py_?  For example,  training train_end2end_resnext.py from 11st  epoch, if I have trained 10 epochs.

Thank you sincerely in advance.

**Comment by terrychenism** [comment]
1. you can use train_end2end_resnet.py to train faster-rcnn with resnet, or you can write resnet symbol for rfcn first, then modify some codes in train_end2end_resnext.

2. simply add --load-epoch = 10 --num_epoch = 20

**Comment by breeze5428** [comment]
Thank you for reply. It works well to run the command as follows:
`python train_end2end_resnext.py  --gpus 0 --num_epoch 15  --num-classes 12`


However, when run the command as follows: 
`python train_end2end_resnet.py  --gpus 0 --num_epoch 15  --num-classes 12 --load-epoch 10`
, then it report an error:

> mxnet.base.MXNetError: [09:40:20] src/io/local_filesys.cc:154: Check failed: allow_null  LocalFileSystem: fail to open "/home/weiliu/projects/mx-rfcn/model/resnext-101-0010.params"

If I run 
`python train_end2end_resnext.py  --gpus 0 --num_epoch 15  --num-classes 12  --load-epoch 10  --pretrained  'model/faster-resnext-101'`
, then it reports

> 
> Traceback (most recent call last):
>   File "train_end2end_resnext.py", line 239, in <module>
>     main()
>   File "train_end2end_resnext.py", line 147, in main
>     args_params, auxs_params= init_model(args_params, auxs_params, train_data, sym, args.pretrained)
>   File "train_end2end_resnext.py", line 52, in init_model
>     del args_params['fc1_weight']
> KeyError: 'fc1_weight'
>

**Comment by breeze5428** [comment]
I fixed the error.  It works well by trained like this:
python train_end2end_resnext.py  --gpus 0 --num_epoch 15  --num-classes 12  --load-epoch 10  --pretrained  'model/faster-resnext-101' --resume
